### ISSUE TITLE
set line-height on headings

### ISSUE THREAD

**Issue by yodasw16** [ScalesCSS/scalescss#25]
Add option to set a different line-height for headings. I think having an overall line-height setting as well as individual variables to set a different line-height for each heading level makes the most sense.

This would need to be implemented in the typography package. There is currently a `$base-line-height` variable set on the body. We would need a new variable called `$heading-line-height` and then one for each heading level that has the default variable as their value.

**Comment by digilou** [comment]
Are you still looking for help, @yodasw16? It looks like you need additions in your typography file?

**Comment by yodasw16** [comment]
Sorry, I fell behind this week. I just added a CONTRIBUTING.md file to the repo. Take a look and thanks for your interest!

**Comment by digilou** [comment]
@yodasw16 I will take a look! This is a neat project you have going on.

**Comment by yodasw16** [comment]
Thanks! Just added  a few details to the issue above.

**Comment by yodasw16** [comment]
Thanks again for contributing!
